GET http://localhost:3000/todos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
###
GET http://localhost:3000/todos/?priority=LOW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
###
GET http://localhost:3000/todos/?search_q=Play
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
###
GET http://localhost:3000/todos/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
###
POST http://localhost:3000/todos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
Content-Type: application/json

{
  "todo": "Learn JS",
  "priority": "MEDIUM",
  "status": "IN PROGRESS"
}
###

PUT http://localhost:3000/todos/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
Content-Type: application/json

{ "status": "DONE" }
###
PUT http://localhost:3000/todos/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
Content-Type: application/json

{ "priority": "HIGH" }
###
PUT http://localhost:3000/todos/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
Content-Type: application/json

{ "todo": "Some task" }
###
DELETE http://localhost:3000/todos/6/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzNDUiLCJpYXQiOjE3NDUzNDgzMDF9.bazUCl0nnCoZQ7MrAJVrOtbrCqUbPTkbAhApweq6t-s
###
POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul12345",
    "password": "rahul@456"
}
###
POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rahul12345",
    "name":"Rahul",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}
###
GET http://localhost:3000/profile/
Authorization: Bearer 